const ShopActionTypes = {
	FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
	FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
	FETCH_COLLECTIONS_FAILTURE: 'FETCH_COLLECTIONS_FAILTURE'
};

export default ShopActionTypes;
